/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.TableStyleRenderer;
import clases.control;
import clases.tableHeaderStyle;
import java.awt.Color;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class esculas extends javax.swing.JDialog {

    control control = new control();
    JComboBox facultad = new JComboBox();
    JButton actualizar = new JButton("actualizar");
    JButton eliminar = new JButton("eliminar");

    /**
     * Creates new form esculas
     */
    public esculas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(33, 76, 102));

        facultad.setName("facultad");
        actualizar.setName("actualizar");
        eliminar.setName("eliminar");

        control.LlenarCombo(jComboBox1, "select facultad from facultades ", 1);
        control.LlenarCombo(facultad, "select facultad from facultades ", 1);
        control.llenarTabla(jTable1, "select escuelas.id, escuela,facultad from escuelas inner join facultades on facultades.id=escuelas.facultades_id order by facultad",
                new Object[]{actualizar, eliminar});

        jTable1.getTableHeader().setDefaultRenderer(new tableHeaderStyle());
        jTable1.setDefaultRenderer(Object.class, new TableStyleRenderer());
        jTable1.setRowHeight(30);
        (jTable1.getColumnModel().getColumn(2)).setCellEditor(new DefaultCellEditor(facultad));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(33, 76, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(33, 76, 102));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("facultad");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setBackground(new java.awt.Color(33, 76, 102));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("escuelas");

        jButton1.setBackground(new java.awt.Color(33, 76, 102));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(33, 76, 102));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("actualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(33, 76, 102));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addComponent(jComboBox1, 0, 417, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jTable1.setBackground(new java.awt.Color(33, 76, 102));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 119, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (jTable1.getSelectedRowCount() != 0) {
            String datos[] = {jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString()};
            control.manipularTablasBD("delete from escuelas where id=?", datos);
            String sql = "select escuelas.id, escuela,facultad from escuelas inner join facultades on facultades.id=escuelas.facultades_id order by facultad";
            control.llenarTabla(jTable1, sql, new Object[]{});
             (jTable1.getColumnModel().getColumn(2)).setCellEditor(new DefaultCellEditor(facultad));
        } else {
            JOptionPane.showMessageDialog(jButton3, "seleccione una fila");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (jTextField1.getText().trim().length() != 0 && jComboBox1.getSelectedIndex() != -1) {
            String datos[] = {jTextField1.getText(), jComboBox1.getSelectedItem().toString()};
            control.manipularTablasBD("insert into escuelas(escuela,facultades_id) values (?,(select id from facultades where facultad=?))", datos);
            String sql = "select escuelas.id, escuela,facultad from escuelas inner join facultades on facultades.id=escuelas.facultades_id order by facultad";
             control.llenarTabla(jTable1, sql, new Object[]{actualizar, eliminar});
              (jTable1.getColumnModel().getColumn(2)).setCellEditor(new DefaultCellEditor(facultad));
        } else {
            JOptionPane.showMessageDialog(jButton1, "campos vacion no se aceptan");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (jTextField1.getText().trim().length() != 0) {
            if (jTable1.getSelectedRowCount() != 0) {
                String datos[] = {jTextField1.getText(), jComboBox1.getSelectedItem().toString(), jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString()};
                control.manipularTablasBD("update escuelas set escuela=? , facultades_id=(select id from facultades where facultad=?) where id=?", datos);
                String sql = "select escuelas.id, escuela,facultad from escuelas inner join facultades on facultades.id=escuelas.facultades_id order by facultad";
                control.llenarTabla(jTable1, sql, new Object[]{actualizar, eliminar});
                 (jTable1.getColumnModel().getColumn(2)).setCellEditor(new DefaultCellEditor(facultad));
            } else {
                JOptionPane.showMessageDialog(this, "seleccione una fila para eliminar");
            }

        } else {
            JOptionPane.showMessageDialog(jButton2, "campos vacion no se aceptan");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:

        jTextField1.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());

        jComboBox1.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());


    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        // TODO add your handling code here:

        Object comp = control.getComponente(evt, jTable1);
        if (comp instanceof JButton) {
            if (((JButton) comp).getName().equals("actualizar")) {
                int res = JOptionPane.showConfirmDialog((JButton) comp, "¿desea actualizar la fila seleccionada?");
                if (res == 0) {//codigo para actualizar
                    String datos[] = {jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString(), jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString(), jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString()};
                    control.manipularTablasBD("update escuelas set escuela=? , facultades_id=(select id from facultades where facultad=?) where id=?", datos);
                    String sql = "select escuelas.id, escuela,facultad from escuelas inner join facultades on facultades.id=escuelas.facultades_id order by facultad";
                    control.llenarTabla(jTable1, sql, new Object[]{actualizar, eliminar});
                    (jTable1.getColumnModel().getColumn(2)).setCellEditor(new DefaultCellEditor(facultad));
                }
            } else if (((JButton) comp).getName().equals("eliminar")) {
                int res = JOptionPane.showConfirmDialog((JButton) comp, "¿desea eliminar la fila seleccionada?");
                if (res == 0) {//metodo para eliminar

                    String datos[] = {jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString()};
                    control.manipularTablasBD("delete from escuelas where id=?", datos);
                    String sql = "select escuelas.id, escuela,facultad from escuelas inner join facultades on facultades.id=escuelas.facultades_id order by facultad";
                    control.llenarTabla(jTable1, sql, new Object[]{actualizar, eliminar});
                    (jTable1.getColumnModel().getColumn(2)).setCellEditor(new DefaultCellEditor(facultad));

                }
            }
        }
    }//GEN-LAST:event_jTable1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(esculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(esculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(esculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(esculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                esculas dialog = new esculas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
